### ISSUE TITLE
Vault CI tests fail on OS X.

### ISSUE THREAD

**Issue by Fraser999** [maidsafe/safe_vault#114]
[Windows failure](http://ci.maidsafe.net:8080/job/maidsafe_vault_win64_status_badge/76/console) and [OS X failure](http://ci.maidsafe.net:8080/job/maidsafe_vault_osx_status_badge/87/console).

The output suggests that the tests are using the example to set up a network.  I don't believe the example should be used in this way.

**Comment by Fraser999** [comment]
Windows failure is fixed by https://github.com/maidsafe/maidsafe_vault/pull/116

**Comment by rossmuir** [comment]
Seeing the [Windows failure again](http://ci.maidsafe.net:8080/job/maidsafe_vault_win64_status_badge/106/console])

**Comment by maqi** [comment]
the executable_test has been removed due to the routing API change.
this issue is no longer apply.
