### ISSUE TITLE
Need an event loop in Vault main

### ISSUE THREAD

**Issue by chandraprakash** [maidsafe/safe_vault#115]
Currently Vault main is using stdin().read_line() to block on main thread (to avoid exiting main thread)

https://github.com/maidsafe/maidsafe_vault/blob/master/src/main.rs#L157-L166

This should be replaced with event handler / signal handler.

**Comment by maqi** [comment]
changed to using sleep, but an event handler / signal handler is still preferred

**Comment by chandraprakash** [comment]
Yes .. I will keep this issue open. We will plan for it in upcoming iteration.

**Comment by maqi** [comment]
Done with the new routing using the channel pattern.
