### ISSUE TITLE
OS X - intermittent - thread '<main>' has overflowed its stack

### ISSUE THREAD

**Issue by rossmuir** [maidsafe/safe_vault#152]
OS X `10.10.4`  -  Rust version `rustc 1.3.0-nightly (118a5c4c3 2015-07-21)` 

When building intermittently seeing   

```
CI-OSX-64:maidsafe_vault ci-mac$ cargo build

thread '<main>' has overflowed its stack
Illegal instruction: 4
```

**Comment by maqi** [comment]
As Ross mentioned in the catch-up meeting, the same issue is observed when compile other libs sometime.
It is suspected the issue is with the rust nightly update, this is waiting for the further verification and investigation.

**Comment by maqi** [comment]
problem no-longer observed after huge refactor of crust/routing/vault.
re-open the issue or report a new one if detect again.
