### ISSUE TITLE
Use of unstable features

### ISSUE THREAD

**Issue by Fraser999** [maidsafe/safe_vault#168]
The following feature gates are being used (which disallow this to be built on the Beta or Stable Rust channels):

[`#![feature(convert, core)]`](https://github.com/maidsafe/safe_vault/blob/master/src/main.rs#L37)
[`#![feature(core)]`](https://github.com/maidsafe/safe_vault/blob/master/src/main.rs#L39)

**Comment by maqi** [comment]
resolved in PR https://github.com/maidsafe/safe_vault/pull/174
