### ISSUE TITLE
No package 'maidsafe_sodiumoxide'

### ISSUE THREAD

**Issue by a-jamesregan** [maidsafe/safe_vault#182]
When running the ```cargo update``` command, an error is returned as [maidsafe_sodiumoxide](https://crates.io/crates/maidsafe_sodiumoxide) does not exist on the crates.io site.

```bash
    Updating registry `https://github.com/rust-lang/crates.io-index`
no matching package named `maidsafe_sodiumoxide` found (required by `safe_vault`)
location searched: registry https://github.com/rust-lang/crates.io-index
version required: *
```

**Comment by Viv-Rajkumar** [comment]
Heya, sorry about that. We were using a fork of the `sodiumoxide` crate which we no longer need to with the original crate getting updated upstream. This change to switch back to default `sodiumoxide` is part of a bigger changeset in https://github.com/maidsafe/safe_vault/pull/180/files#diff-80398c5faae3c069e4e6aa2ed11b28c0L24

Once that changeset gets merged in, this issue should be resolved.

**Comment by a-jamesregan** [comment]
Ah cool, I can't wait!

**Comment by maqi** [comment]
is resolved in PR https://github.com/maidsafe/safe_vault/pull/180
