### ISSUE TITLE
'ConnectionManager bootstrap loop' panicked

### ISSUE THREAD

**Issue by rossmuir** [maidsafe/safe_vault#224]
Ubuntu 15.04 / `rustc 1.4.0-nightly (7d78f2d33 2015-09-01)` / Release build

```
$ RUST_LOG=info ./safe_vault 
INFO:routing::routing_node: RoutingNode Client(6c5b1b..fa7f19) listens on [Tcp(V4(192.168.1.82:5483))]
thread 'ConnectionManager bootstrap loop' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: NotConnected, error: StringError("os error") }) }', ../src/libcore/result.rs:734
^C
```

**Comment by rossmuir** [comment]
I have been unable to recreate this - even with `cargo clean` and rebuilding

**Comment by maqi** [comment]
This is probably due to unwrap being used unsafely in crust (connection_manager).
Better raise the issue in crust lib and ask guys to remove all unsafe use of unwrap.
