### ISSUE TITLE
when a PmidNode leaving network

### ISSUE THREAD

**Issue by maqi** [maidsafe/safe_vault#259]
The current mechanism relies on a DM receiving a get_request to a data stored in that pmid_node,
then after a while the DM can then notice no get_response from that pmid_node, then mark that node as failure, remove it from records then notify PMs of that pmid_node, and then carry out a get and replication if not enough copies.
However, there are three issues:
1, if there are no get_request to the data, and pmid_nodes keeps leaving the network, there is risk the data will be vanished eventually.
2, chunks stored on the leaving pmid_node have to have their records to be updated one by one individually, which may not be efficient.
3, when caching is enabled, the get_response can not ensured the targeted pmid_node is still alive

**Comment by maqi** [comment]
One solution is to utilize the churn event, i.e. when DM receiving a churn down, it go through all the records and remove the reported leaving node from the records.

**Comment by dirvine** [comment]
It should do that and create a new copy stored on closest to the address again (this way all DM will choose same PmidNode)

**Comment by Fraser999** [comment]
Resolved in https://github.com/maidsafe/safe_vault/pull/293.
