### ISSUE TITLE
DM can not fetch data for replication

### ISSUE THREAD

**Issue by maqi** [maidsafe/safe_vault#261]
When DM detects a failing pmid_node, it needs to fetch the data from alive pmid_nodes then to replicate it to new pmid_node.
However, the current accumulation mechanism in routing mark the get request from DM to pmid_node based on DataRequest only, which will think the Fetch request is same as the original get_request from client.
This blocks the alive pmid_nodes receiving get_request resulting in a never completed replication.

Following options are available to resolve the issue:
1, DM holds a cache of received data. however this will be duplicated with the cache in routing
2, DM asking routing for a cache copy, if failed, send out fetch request to pmid_nodes. However, this enforce the cache window must be consistent with the accumulator time_out window, which in many case will be not and hard to achieve.
3, Introduce a random bit in routing api (simillar to the get_request from Client to DM, or a cause field?) so accumulator can treat them differently.

**Comment by benjaminbollen** [comment]
> However, the current accumulation mechanism in routing mark the get request from DM to pmid_node based on DataRequest only, which will think the Fetch request is same as the original get_request from client.

I don't believe this is true @maqi. the source and destination authority is also taken as part of the unique identification of the routing message.

**Comment by benjaminbollen** [comment]
> This blocks the alive pmid_nodes receiving get_request resulting in a never completed replication.

It could be blocked by the full source group not reaching the treshold in at the destination?

**Comment by benjaminbollen** [comment]
option 1 and 2 don't seem plausible to me
> 3, Introduce a random bit in routing api (simillar to the get_request from Client to DM, or a cause field?) so accumulator can treat them differently.
I have explained the reasoning here; the original proposal was for providing a cause to the vaults;  we decided against it though (https://github.com/maidsafe/routing/pull/602)
After that decision it was evaluated and implemented for it to work without such an external cause.  If this needs re-examining, then for sure yes, we should look at it in more detail.

**Comment by maqi** [comment]
once https://github.com/maidsafe/safe_vault/issues/263 got resolved and implemented,
the code can be used to verify whether this issue valid or not.

currently leaving this issue as open till being verified by Issue https://github.com/maidsafe/safe_vault/issues/263

**Comment by maqi** [comment]
@benjaminbollen : unfortunately, for this scenario, the source and destination will all be the same, i.e. the tuple (source, destination, data_request) will stays same.

This is because DM can only detect a failed pmid_node through first get_request, where get_requests got forwarded from DM to PN due to this first get_request is: (DM(data_name), PN(alives), data_request(data_name))
Once a failed pmid_node detected, when DM needs to fectch a copy, such fetch request will also be : (DM(data_name), PN(alives), data_request(data_name))
which will be the exactly same as the previously forwarded one (except about 10 seconds later), and this will be filtered out by the current accumulator and never be able to reaching the targeted pmid_node

**Comment by benjaminbollen** [comment]
Thanks @maqi but we have discussed this issue already several times.  It does not seem that we are progressing though.  If the behavior of SAFE vaults is as outlined in the language of the network this problem should not exist, right?

**Comment by maqi** [comment]
@benjaminbollen : This is for the error handling part and a possible client use case as well.
The document says a replication and fetch from network is required in case of failure, so I don't understand why you say the problem should not exist.

Yes there was discussions previously, but as I remember we have not reached any solution to resolve it.

**Comment by Fraser999** [comment]
Resolved in https://github.com/maidsafe/safe_vault/pull/293.

**Comment by maqi** [comment]
This issue is still not resolved by the PR https://github.com/maidsafe/safe_vault/pull/293 .
However, the issue itself is due to the current design in routing.

It still needs to be discussed with routing whether duplicated identical request shall be supported.
May re-open this issue or raise it to routing lib if necessary

**Comment by Fraser999** [comment]
Yup - sorry - I shouldn't have closed this.

**Comment by maqi** [comment]
From routing perspective, it has cache which once enable, any duplicated identical request shall get response immediately.
This cleans the concern that DM needs the copy to carry out replication:
when routing blocks the duplicated call, the data shall still sits in the cache and can be used to answer;
when routing doesn't have that the data in cache, the filter window shall also get expired which allows duplicated call to be forwarded.

Although this may raise a concern that a leaving pmid_node can not be detected in-time due to the cache, such chance shall be quite tiny after the implementation of PR https://github.com/maidsafe/safe_vault/pull/293 regarding Issue https://github.com/maidsafe/safe_vault/issues/259, which enables DM being notified of leaving nodes by routing and then carry out replication actively.

So currently this issue can be considered as no longer valid, and can now be closed.
