### ISSUE TITLE
DM trigger fetch of data immediately when not enough alive nodes after removing failed pmid_node

### ISSUE THREAD

**Issue by maqi** [maidsafe/safe_vault#263]
Currently, fetching of data is solely depends on client's request, leaving a high risk of losing data.
When DM removing failed pmid_node, Replication shall be triggered immediately if not enough alive nodes.
If there is no data can be fetched from cache, a fetch shall be fired to all alive nodes that not in the current on_geting_gets list.

once the above is implemented, the current test vault::test::network_churn_down_two_nodes_immutable_data_test can be modified to have the new_client asking for a random data just once to cover the testing.

**Comment by maqi** [comment]
according to the comments from Ben in the https://github.com/maidsafe/safe_vault/issues/261
this shall be achievable with the current implementation of routing.

**Comment by Fraser999** [comment]
Resolved by https://github.com/maidsafe/safe_vault/pull/293.
