### ISSUE TITLE
Threads are created exponentially

### ISSUE THREAD

**Issue by Ghaunt** [maidsafe/safe_vault#266]
I do some test on my main computer and with my laptop (both with arch-linux 64-bit) to find what is going on with the threads.
The first vault start and it's fine. But after each vault added to the network more threads are created or even doubled compared to the previous started vault.

I have to increase PID and THREADS limit to do this test or else it crash only after aroung 10 vaults
I started 30 vaults on my main computer with having a total of over 200000 threads created. After I start only one vault on the laptop (keeping the kernel limit to default PID: 32k) and BANG, crashed. Too much threads.

The error is with: Resource temporarily unavailable.

Further testing: It happen much more likely when the bootstrap cache is getting bigger.

>thread 'Service::connect' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 11, message: "Resource temporarily unavailable" } }', ../../sources/rust/src/libcore/result.rs:736
thread 'State::bootstrap_off_list' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 11, message: "Resource temporarily unavailable" } }', ../../sources/rust/src/libcore/result.rs:736
thread 'Service::connect' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 11, message: "Resource temporarily unavailable" } }', ../../sources/rust/src/libcore/result.rs:736
thread 'Service::run loop' panicked at 'explicit panic', /home/ghaunt/.cargo/registry/src/github.com-0a35038f75765ae4/crust-0.4.0/src/service.rs:308
thread 'Service::connect' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 11, message: "Resource temporarily unavailable" } }', ../../sources/rust/src/libcore/result.rs:736
thread '<unnamed>' panicked at 'assertion failed: sender.send(Box::new(cmd)).is_ok()', /home/ghaunt/.cargo/registry/src/github.com-0a35038f75765ae4/crust-0.4.0/src/service.rs:371
thread 'Service::run loop' panicked at 'explicit panic', /home/ghaunt/.cargo/registry/src/github.com-0a35038f75765ae4/crust-0.4.0/src/service.rs:308
thread '<unnamed>' panicked at 'assertion failed: sender.send(Box::new(cmd)).is_ok()', /home/ghaunt/.cargo/registry/src/github.com-0a35038f75765ae4/crust-0.4.0/src/service.rs:371
>

Continuing there: https://github.com/maidsafe/crust/issues/346

**Comment by maqi** [comment]
Thank you very much for reporting the issue.
Noticed you have investigated the issue further and report it in crust lib, which is the proper place to put.
I have notified the crust lib maintainer to pay attention to it.
As this issue is not in vault lib directly, I am closing this.
