### ISSUE TITLE
Change error-handling in handle_put of PmidNode persona

### ISSUE THREAD

**Issue by Fraser999** [maidsafe/safe_vault#267]
[This line](https://github.com/maidsafe/safe_vault/blob/9c36ca33cd8f15e4128f612101a4a7fae675d31d/src/pmid_node/mod.rs#L138) should not cause the for loop to exit.

Instead we should remove the corrupt chunk and continue.

**Comment by maqi** [comment]
Resolved by PR https://github.com/maidsafe/safe_vault/pull/286
