### ISSUE TITLE
Chunkstore should clean up after itself

### ISSUE THREAD

**Issue by Fraser999** [maidsafe/safe_vault#269]
Chunkstore should remove any added dirs/files from the local disk on destruction.

It should also remove previous chunkstores' remnants in case the previous run crashed without cleaning up.  This is not straightforward if we are to support multiple instances of vault running concurrently.  We'd maybe have to name the dir with the current process' PID and check for that PID running before erasing the dir for example.

**Comment by maqi** [comment]
In network test, vaults are being executed as spawned threads, and also vault has PmidNode and StructruedDataManager using separate chunk_store instance.
So the dir structure may needs to be :   <process_id>/<thread_id>/<persona_name>

**Comment by Fraser999** [comment]
Agreed, although I think the cleanup of previous runs should only be looking at PID; I don't think we need per-thread cleanup.

Also, I think I'd go for Vault ID rather than thread name (I think we only have access to [`Thread::name()`](https://doc.rust-lang.org/nightly/std/thread/struct.Thread.html#method.name)).  I'd like to see all threads named to help with debugging (I'm planning to propose it in the style RFC), but either way, all threads will have the same name for every vault, or they'll all have `None`.
