### ISSUE TITLE
safe_vault hangs 

### ISSUE THREAD

**Issue by rossmuir** [maidsafe/safe_vault#270]
Intermittently `safe_vault` hangs at the stage below and does not join the network
```
INFO:routing::routing_node: RoutingNode Client(5e21e0..f7fae5) listens on [Tcp(V4(127.0.0.1:5483)), Tcp(V4(45.79.93.11:5483))]
INFO:routing::routing_core: Routing Client bootstrapped.
INFO:safe_vault::vault: Vault 000000..000000 received an event from routing : Bootstrapped
```

**Comment by maqi** [comment]
could you give more description regarding the testing environment and how to reproduce it?
it seems routing fired the bootstrap event, but never fired the churn event for some reason.

**Comment by Ghaunt** [comment]
It happen to me too, I though it was normal. I reproduce it be opening safe_vault one after other until it happen. I just do it and happened after I opened 40th one.

**Comment by rossmuir** [comment]
@maqi  sorry it was on a droplet network 18 nodes all on Ubuntu 15.04.  You reproduce it by launching safe_vault one after another as @Ghaunt  reports. I was running `RUST_LOG=info ./safe_vault`

**Comment by Ghaunt** [comment]
It may be the same problem.
https://github.com/maidsafe/crust/issues/342

**Comment by G-Ray** [comment]
It seems ```rm ~/.config/safe_vault/safe_vault.bootstrap.cache``` is a workaround

**Comment by Ghaunt** [comment]
G-Ray I do some test with erasing the bootstrap.cache before starting a vault and that doesn't help.

My test setup is a start a vault on my laptop for the entry point because broadcast message does not rebounce back to the same computer here. Don't know why.

And on my main computer, I do the main part, erase the cache and start a vault. I do this with a simple script to be faster. The hang still happen sometimes.

I will still try to investigate further. But I put my guess it's on the crust or routing lib.

**Comment by rossmuir** [comment]
I can also confirm the removal of the bootstrap.cache does not help

**Comment by maqi** [comment]
vault may need to have a `timeout` instead of the current `wait forever` approach.
this will get vault process `quit on failure`

**Comment by Fraser999** [comment]
@G-Ray if `~/.config/safe_vault/safe_vault.bootstrap.cache` is populated with many dead endpoints (i.e. Vaults which are no longer running) then this can look like the process has hung.  In fact, Routing is just iterating through this list until it makes a connection.  From memory, the list is capped at 1500 entries, but obviously it can take a considerable time to work through such a list trying to connect to each entry.

@maqi I think the "wait forever" approach is the correct one.  If a machine loses connectivity for an extended period, the Vault should just reconnect whenever possible after that, not stop running.  If we're adding a timeout, I think this should be used for tests only.

**Comment by Ghaunt** [comment]
>
DEBUG:routing::routing_node: Queuing message for processing ourselves
DEBUG:routing::routing_node: Accumulator threshold is at 5
DEBUG:routing::routing_node: Adding message from add5d9..3a4a4c to accumulator
DEBUG:routing::routing_node: Sending InternalRequest(CacheNetworkName(PublicId(name:0a2534..af6a27), SignedToken)) to 8 target connection(s)
DEBUG:routing::routing_node: Queuing message for processing ourselves
DEBUG:routing::routing_node: Accumulator threshold is at 5
DEBUG:routing::routing_node: Adding message from af9408..967af4 to accumulator
DEBUG:routing::routing_node: Sending InternalRequest(CacheNetworkName(PublicId(name:00aa71..e0898c), SignedToken)) to 8 target connection(s)
DEBUG:routing::routing_node: Queuing message for processing ourselves
DEBUG:routing::routing_node: Accumulator threshold is at 5
DEBUG:routing::routing_node: Adding message from dcf22f..8dbd83 to accumulator
>

It's one of the reason it hang. It appear on almost other terminal. The other reason I think of is "message from unidentified connection" appear in mass in other terminal when it hang.

**Comment by maqi** [comment]
@Fraser999 : in case crust does not able to establish a connection after everything has been tried, I do prefer it can throw something (or maybe just a panic? ), so that the vault process can stop by itself on failure.
Looking at the scenario to re-create this reported issue: keeps starting up a vault on the same machine till it hangs. If vault allows an establish attempt keeps going forever, this hanging issue is guaranteed to  happen.
I agree putting a timeout on vault level will be not suitable, but can crust/routing tell whether all means have been tried and it is really the time to STOP ?

**Comment by Fraser999** [comment]
> after everything has been tried

I guess this is where I have the problem - how do we define that?  For example, the user could be offline for a week and then physically move to an area where Internet connectivity is restored.  I don't see a reason why the Vault can't be running for that entire duration (assuming it's consuming minimal power during this) and automatically reconnect.

> but can crust/routing tell whether all means have been tried and it is really the time to STOP ?

To me, this time is when the user uninstalls the Vault :)

I do agree that we need a way to check that a Vault has connected when it's expected to.  That's possibly even something which could form part of a production API e.g. if we ever want to have a system tray icon showing the Vault's status.  If we have that, tests can wait for that signal for a predetermined time and fail if it doesn't connect without changing the main loop style we currently have.

**Comment by Ghaunt** [comment]
With the recent change this issue no longuer happen to me but it is likely replaced with somethings else that the routing are not able to maintain properly a connection with all the attemps it made sometimes. Making the vault useless.

**Comment by maqi** [comment]
The hanging issue itself is due to crust/routing's incorrect handling of bootstrapping.
As it is argueable whether vault shall step in to terminate the indefinite loop to make a self stop, this issue is currently being closed.
