### ISSUE TITLE
Network test hangs on Windows

### ISSUE THREAD

**Issue by Fraser999** [maidsafe/safe_vault#279]
The `vault::test::network_test` hangs on Windows after all tests have run, regardless of it passing or not.

**Comment by Fraser999** [comment]
Initial debugging seems to show the root cause to be the test not telling the local network of vaults to stop!

We pass a channel receiver when we construct vaults (https://github.com/maidsafe/safe_vault/blob/72989bf2a331248d3dea105cf851f4fc84e30376/src/vault.rs#L44) and when the corresponding sender passes a `0` we break out of the main event loop (https://github.com/maidsafe/safe_vault/blob/72989bf2a331248d3dea105cf851f4fc84e30376/src/vault.rs#L92-L106).

In the network test, we need to send this `0` to each of the vaults in the testnet.  However, there are two traps here.

Firstly, we need to ensure the signal is sent regardless of the test passing or failing (so e.g. we could use a RAII object in the scope of the test to send the `0`s).

Secondly, we need to ensure that the channel senders live long enough to allow the vaults to receive the `0`s.  If we send the message and then immediately destroy the channel sender, it frequently isn't received.  So I guess we need to wait for a response from the vaults to indicate that they're terminating, or something like that.

**Comment by maqi** [comment]
Just put as a record, the work (PR https://github.com/maidsafe/safe_vault/pull/277) regarding task https://maidsafe.atlassian.net/browse/MAID-1432 resolving issue https://github.com/maidsafe/safe_vault/issues/269 , contains the code sending termination signal to vaults and then to routing.
