### ISSUE TITLE
chunk_store.put() shall return Result<(), error>

### ISSUE THREAD

**Issue by maqi** [maidsafe/safe_vault#289]
This allows persona code to recognize and handle failure puts due to over fill (or any other failure), and notify other correspondent personas.

Be noted, this issue also involves the work of modifying the error handling part in put flow.

also, once such change be deployed, the removed tests in the commit https://github.com/maidsafe/safe_vault/commit/fde9e82babfd8f7fcaa5c0e2c00872031cc8fae6 shall be restored.

**Comment by Fraser999** [comment]
ChunkStore is now in its own crate and its API matches what is requested here.
