### ISSUE TITLE
safe_vault uses 100% CPU no matter what

### ISSUE THREAD

**Issue by davidkazlauskas** [maidsafe/safe_vault#298]
I've compiled safe_vault at 0507ad3f3f5a264e3618d914c7220fa618fb210f commit, didn't test previous ones, but when I run it on ubuntu 14.04 x86_64 machine (didn't test anywhere else) safe_vault seems to be always stuck at 100% CPU. Tried 10 vaults at once, now due to contention it's lower than 100% per each core but it's around 60-100 at all times. I don't think this is normal.

**Comment by Fraser999** [comment]
Thanks for the report.

I had tried swapping the `thread::sleep_ms(1)` with `thread::yield_now()` in the main event loop while working on another task and forgot to revert the changes.  https://github.com/maidsafe/safe_vault/pull/299 should fix this.
