### ISSUE TITLE
the zip files of 0.6.0 release don't have subfolder structures included but directly the binaries

### ISSUE THREAD

**Issue by subscribernamegoeshere** [maidsafe/safe_vault#433]
Hi there.
The zip files of v0.6.0 here of the safe_vault don't come with subfolders included, like many or most of the other releases e.g. demo launcher and other stuff. At least I have checked the win32 and win-x64 ones.

Please fix this and put your files into subfolders named properly to not cause chaos on the users disk. Thanks.

**Comment by maqi** [comment]
thanks for raising the issue, this shall now be resolved in the v0.7.0 release.
