### ISSUE TITLE
Add a CI test which stores up to allowed Client limit

### ISSUE THREAD

**Issue by Fraser999** [maidsafe/safe_vault#453]
We should add a test similar to the existing CI one `fill_network` which, rather than filling the DMs, instead fills the Client's account.  This should assert that the Client is consistently notified with failure once its account is full.

**Comment by maqi** [comment]
won't a unit_test shall be enough? or you mean this shall be tested against churn as well?
if the latter, we may need to consider bring back passing down config.

**Comment by maqi** [comment]
once PR https://github.com/maidsafe/safe_vault/pull/456 got merged, this can be added as a unit test of repeatedly putting combination of small immutable and structured data.
