### ISSUE TITLE
SAFE Vault 0.8.0 crashes on startup with error illegal instruction

### ISSUE THREAD

**Issue by Onaka** [maidsafe/safe_vault#469]
So I rented an ARM server from Scaleway and figured I'd pop on a vault running the community test net.
The server is currently running Arch Linux.
Output of the program:
./safe_vault 
Illegal instruction (core dumped)

Some information about the system:
uname -a
Linux scw-7c2d7c 4.4.0-std-1 #1 SMP Wed Jan 20 13:27:11 UTC 2016 armv7l GNU/Linux

cat /proc/cpuinfo 
processor   : 0
model name  : ARMv7 Processor rev 2 (v7l)
BogoMIPS    : 50.00
Features    : half thumb fastmult vfp edsp thumbee vfpv3 tls idiva idivt vfpd32 lpae 
CPU implementer : 0x56
CPU architecture: 7
CPU variant : 0x2
CPU part    : 0x584
CPU revision    : 2

processor   : 1
model name  : ARMv7 Processor rev 2 (v7l)
BogoMIPS    : 50.00
Features    : half thumb fastmult vfp edsp thumbee vfpv3 tls idiva idivt vfpd32 lpae 
CPU implementer : 0x56
CPU architecture: 7
CPU variant : 0x2
CPU part    : 0x584
CPU revision    : 2

processor   : 2
model name  : ARMv7 Processor rev 2 (v7l)
BogoMIPS    : 50.00
Features    : half thumb fastmult vfp edsp thumbee vfpv3 tls idiva idivt vfpd32 lpae 
CPU implementer : 0x56
CPU architecture: 7
CPU variant : 0x2
CPU part    : 0x584
CPU revision    : 2

processor   : 3
model name  : ARMv7 Processor rev 2 (v7l)
BogoMIPS    : 50.00
Features    : half thumb fastmult vfp edsp thumbee vfpv3 tls idiva idivt vfpd32 lpae 
CPU implementer : 0x56
CPU architecture: 7
CPU variant : 0x2
CPU part    : 0x584
CPU revision    : 2

Hardware    : Marvell Armada 370/XP (Device Tree)
Revision    : 0000
Serial      : 0000000000000000

**Comment by octol** [comment]
Thanks for filing the issue. There is a new release available which is significantly re-architectured and hopefully fixes many of the reported technical issues
