### ISSUE TITLE
vault causes whole system to hang.

### ISSUE THREAD

**Issue by Blindsite** [maidsafe/safe_vault#474]
Again I don't know what is considered "normal".   But I observed as I was running the vault that parts of my whole system started to hang, particularly the text editor I was using to view the logs and the terminal.   My web browser wasn't too happy either but it didn't crash.  The text editor however did, a couple times and the terminal became non responsive though it did continue to run the vault even though it seemed to stop displaying new text after awhile.   I know this because after I terminated the vault program a bunch of new text suddenly appeared.   I think this could become a problem if this continues and people start running series data though their vaults.

**Comment by rossmuir** [comment]
Thank you for feeding back, in this testing phase this is very much pre-release software and comes with the associated risks of running such software. We are aware that sometimes a Vault can be resource hungry and the Devs are working on this. Thank you for participating in the testing.
Cheers
Ross
