### ISSUE TITLE
routing bug?

### ISSUE THREAD

**Issue by tjterris** [maidsafe/safe_vault#492]
Not sure if this is a bug but figured I'd report it.

After `INFO 20:53:57.291247000 [routing::core core.rs:413] | Node(8ad3ab..) PeerId(717c..) - Routing Table size:   3 |`

I got several lines of

`ERROR 20:53:57.488095000 [routing::core core.rs:648] Node(8ad3ab..) Failed to prepare connection info: Nat(Io(Error { repr: Os { code: 24, message: "Too many open files" } }))`

before getting 
`thread 'IGD-Address-Mapping' panicked at 'could not initialize thread_rng: Too many open files (os error 24)', ../src/libstd/rand/mod.rs:159`

eventually it got past it.

Hope I didn't waste your time!

**Comment by ustulation** [comment]
Hey @tjterris - that is coming from Crust.
Ya we do run into that in our simulation when we have many instances of crust running. So if you could let us know your O.S (if linux - then distro too and a printout of `ulimit -a`), how many vaults and how many clients you ran on the same machine.

**Comment by tjterris** [comment]
OSX 10.10.5

I would see this error typically when running the first vault.  I've only been running one client.

**Comment by octol** [comment]
With that new release we've swapped Crust for quic-p2p, so hopefully this should have gone away. Thanks for reporting it!
