### ISSUE TITLE
Running Vault Broke my internet connexion.

### ISSUE THREAD

**Issue by digipl** [maidsafe/safe_vault#493]
Windows 7 64 bits

After one or two minutes, running vault broke my internet connexion (Test three times). Possibly is my very old router (ADSL asymmetric 20/2 Mb.)

Launcher and Apps work without problems
[Node.zip](https://github.com/maidsafe/safe_vault/files/315749/Node.zip)

**Comment by chrisfoster** [comment]
Same issue here also using Windows 7 64 bits and ADSL asymmetric 20/2 Mb

Had multiple instances of clearnet DNS resolution failing and then after 5 days of running a vault the ADSL connection was dropped.

Upon ADSL re-connection, the first run of safe_vault.exe failed, the second run stayed up and took around 4 rounds of network connection attempts until it joined.

**Comment by octol** [comment]
In the new re-architectured Vault version the network layer is completely changed so hopefully this should not happen anymore. Thanks for reporting!
