### ISSUE TITLE
Warning: Prepared connection info for PeerId...?

### ISSUE THREAD

**Issue by chadrickm** [maidsafe/safe_vault#495]
INFO 08:29:14.062279800 [routing::stats stats.rs:158] Stats - Direct - NodeIdentify: 69, NewNode: 1181, ConnectionUnneeded: 0
INFO 08:29:14.062279800 [routing::stats stats.rs:162] Stats - Hops (Request/Response) - GetNodeName: 1/0, ExpectCloseNode: 0, GetCloseGroup: 155/25, ConnectionInfo: 330, Ack: 723, GroupMessageHash: 0
INFO 08:29:14.062279800 [routing::stats stats.rs:172] Stats - User (Request/Success/Failure) - Get: 2/2/0, Put: 0/0/0, Post: 0/0/0, Delete: 0/0/0, GetAccountInfo: 0/0/0, Refresh: 11
**WARN 08:29:56.796595400 [routing::core core.rs:683] Node(98e7a9..) Prepared connection info for PeerId(04a6..) as 996852.., but already tried as 996852...
WARN 08:34:41.364375600 [routing::core core.rs:1903] Node(98e7a9..) Prepared connection info for PeerId(b3e7..) as 9d8ee0.., but already tried as 9d8ee0...
WARN 08:34:44.268204000 [routing::core core.rs:1903] Node(98e7a9..) Prepared connection info for PeerId(9d3f..) as d8fec2.., but already tried as d8fec2...**
INFO 08:35:00.907978000 [routing::stats stats.rs:151] Stats - Sent 3000 messages in total, comprising 1652061 bytes, 1 uncategorised, routes/failed: [751, 4, 3, 3, 3, 3, 3, 3]/3
INFO 08:35:00.907978000 [routing::stats stats.rs:158] Stats - Direct - NodeIdentify: 69, NewNode: 1181, ConnectionUnneeded: 0
INFO 08:35:00.907978000 [routing::stats stats.rs:162] Stats - Hops (Request/Response) - GetNodeName: 1/0, ExpectCloseNode: 0, GetCloseGroup: 313/58, ConnectionInfo: 461, Ack: 901, GroupMessageHash: 0
INFO 08:35:00.907978000 [routing::stats stats.rs:172] Stats - User (Request/Success/Failure) - Get: 2/2/0, Put: 0/0/0, Post: 0/0/0, Delete: 0/0/0, GetAccountInfo: 0/0/0, Refresh: 11
**WARN 08:42:41.304549700 [routing::core core.rs:1903] Node(98e7a9..) Prepared connection info for PeerId(b3e7..) as 9d8ee0.., but already tried as 9d8ee0...
WARN 08:42:44.296698700 [routing::core core.rs:1903] Node(98e7a9..) Prepared connection info for PeerId(9d3f..) as d8fec2.., but already tried as d8fec2...**

**Comment by afck** [comment]
Thank you for reporting this! That's definitely a bug, but it shouldn't really affect functionality. Probably d8fec2.. was even added to your routing table a bit later.

Anyway, we will address this soon: we are going to reorganise connection handling a bit anyway to get rid of problems like this one.

**Comment by lionel1704** [comment]
A newly architectured vault has been released which is being integrated with the latest routing library which uses quic_p2p for network connections. Hence, I'm closing this issue.
