### ISSUE TITLE
v0.9.0 linux x86, "Failed to start listening"

### ISSUE THREAD

**Issue by wrnice** [maidsafe/safe_vault#496]
Hello, 

trying to run the v0.9.0 vault on a x86 linux laptop with fedora 21,

I get :

 ./safe_vault 

INFO 19:25:12.135470316 [safe_vault safe_vault.rs:96] 
# Running safe_vault v0.9.0

INFO 19:25:14.647747832 [routing::core core.rs:1032] Client(19735e..) Running listener.
ERROR 19:25:14.649626273 [routing::core core.rs:530] Client(19735e..) Failed to start listening.

then the process quits nicely.

Node.log says : 

INFO 19:25:12.135532053 [safe_vault safe_vault.rs:96] 
# Running safe_vault v0.9.0

DEBUG 19:25:12.142906284 [crust::main::service service.rs:552] Network name: Some("2016_06_14_test_network_4")
DEBUG 19:25:14.539241052 [crust::main::active_connection active_connection.rs:57] Entered state ActiveConnection: PeerId(003c..) -> PeerId(b499..)
DEBUG 19:25:14.539814355 [routing::core core.rs:550] Disconnected(19735e..) Received BootstrapConnect from PeerId(b499..).
DEBUG 19:25:14.540333323 [routing::core core.rs:1063] Disconnected(19735e..) - Sending ClientIdentify to PeerId(b499..).
DEBUG 19:25:14.647249815 [routing::core core.rs:1276] Client(19735e..) - State changed to client, quorum size: 5.
INFO 19:25:14.648711042 [routing::core core.rs:1032] Client(19735e..) Running listener.
ERROR 19:25:14.649250543 [crust::main::connection_listener mod.rs:78] Error starting tcp_listening_socket: Io(Error { repr: Os { code: 92, message: "Protocol not available" } })
ERROR 19:25:14.649700651 [routing::core core.rs:530] Client(19735e..) Failed to start listening.
Node.log (END)

This is behind a residential DSL nat router.

I hope this can help ! I'd be glad to provide additional details if needed.

Regards, keep up rocking

**Comment by ustulation** [comment]
This is related to Crust.
Can you pls print the kernel version you are running ?

**Comment by octol** [comment]
Since this is a Crust issue, which we're not using anymore in the latest vault version I'm closing this. Thanks for reporting it!
