### ISSUE TITLE
Can't seem to launch a vault on my phone

### ISSUE THREAD

**Issue by Blindsite** [maidsafe/safe_vault#497]
I'm trying out the new arm vault on my android phone (android v 5.0.1) and I can't seem to launch the vault.   I downloaded it, extracted it and tried to open it and nothing.   It doesn't open as an executable.   So where do I go from here.   Are there some prerequisites I need to install to get this running or something?

**Comment by afck** [comment]
The ARM builds are just for Linux at the moment. As there are some significant differences between Android and stock Linux, these will be separate builds.

In the long run, we definitely plan to support Android, but it's not on our short-term agenda at the moment unfortunately, so I'll close this issue for now.
