### ISSUE TITLE
Arithmetic Operation Overflowed

### ISSUE THREAD

**Issue by hintofbasil** [maidsafe/safe_vault#508]
Vault crashed with an arithmetic operation overflowed error.  This happened very shortly after the reboot of the [community test net](https://forum.safenetwork.io/t/community1-test-network-has-restarted-join-us/).  I was also registering through safe_launcher and had just shut down a node running along side the current one.  Registering on the network failed.  The vault was compiled from the master node that day (9eab4dd4aab557e6676302b798cf7a3680d4a74f) and the launcher was the latest release.

I was only able to get the console output as I was running multiple nodes from the same folder and another one had written to Node.log.  However I have attached the console output [vault_log.txt](https://github.com/maidsafe/safe_vault/files/333700/vault_log.txt)
.

**Comment by lionel1704** [comment]
A newly architectured vault has been released. Hence, I'm closing this issue.
