### ISSUE TITLE
Debian arm safe vault start up

### ISSUE THREAD

**Issue by josephm1** [maidsafe/safe_vault#527]
Vault isn't starting up. Although tested in linux deploy through android.﻿

Error creating appender 'async file': Read-only file system (os error 30) 
Error creating config: Reference to nonexistent appender: 'async file' 
Error creating config: Reference to nonexistent appender: 'async file' 
Cannot start vault due to error : FileHandler(IoError(Error { repr: 0s { code: 2, message: "No such file or directory" } })) INFO 23:12:59.747251084 [safe vault safe vault.rs:100]

**Comment by afck** [comment]
At the moment the vault tries to create a log file in the directory you run it _from_, i. e. the current directory. Do you have write access to that?

**Comment by josephm1** [comment]
Sorry new issue 

﻿Error creating appender 'async file': Read-only file system (os error 30) 
Error creating config: Reference to nonexistent appender: 'async file' 
Error creating config: Reference to nonexistent appender: 'async file' 
Cannot start vault due to error : FileHandler(IoError(Error { repr: 0s { code: 2, message: "No such file or directory" } })) INFO 23:12:59.747251084 [safe vault safe vault.rs:100]

**Comment by josephm1** [comment]
sorry wrong errror

INFO 10:32:51.859076918 [safe_vault safe_vault.rs:180] 

Running safe_vault v0.10.2 

INFO 10:32:54.274455752 [routing::core core. 5:10901 Client(a65816..) Attempting to start listener. 

ERROR 10:32:54.275569242 [routing::core core.rs:54l] Client(a65816..) Failed to start listening.

**Comment by canndrew** [comment]
@josephm1 What kernel version are you running?

**Comment by josephm1** [comment]
Well Debian is being run in Linux deploy in a chrooted environment on android but here is the android kernel as I think that is the kernel it is using.
Kernel version 

3.4.1 12-Resurrected_Kernel-gc70f2a3 varun@varun-MS-7923 #1 Thu Jun 2310;29:08 IST 2016

**Comment by canndrew** [comment]
Ah, we (currently) only support kernel versions > 3.9. Linux 3.9 introduces the SO_REUSEPORT option which is useful for discovering the external addresses of tcp sockets. We need to add a fallback for when it's not available.

**Comment by josephm1** [comment]
Thanks for replying so quickly, guess I won't be setting  a vault on android today.
