### ISSUE TITLE
Repeat Acknowledgement issues.

### ISSUE THREAD

**Issue by Blindsite** [maidsafe/safe_vault#531]
Okay this error keeps cropping up (this is the second time I think this has happened) on my windows vault.   I'm on Win 7, using the 10.2 vault.   It'll run fine for awhile and then I'll get something like this:

DEBUG 22:54:36.149591800 [routing::core core.rs:1299] Node(1b7564..) Received ConnectionUnneeded from PeerId(1aa3..).
DEBUG 22:54:37.582673800 [routing::core core.rs:1299] Node(1b7564..) Received ConnectionUnneeded from PeerId(1aa3..).
ERROR 22:54:37.781685100 [routing::core core.rs:2248] Node(1b7564..) Failed to send ack: FilterCheckFailed
ERROR 22:55:13.799745300 [routing::core core.rs:2248] Node(1b7564..) Failed to send ack: FilterCheckFailed
DEBUG 22:57:16.935788200 [routing::core core.rs:1902] Node(1b7564..) - Message unable to be acknowledged - giving up. UnacknowledgedMessage { signed_msg: SignedMessage { content: RoutingMessage { src: ClientManager(name: 101f18..), dst: ClientManager(name: 101f18..), content: UserMessagePart { 1/1, priority: 1  c06cb3b339e367f4} }, public_id: PublicId(name: 1b7564..), signature: .. }, route: 8, timer_token: 3656 }
DEBUG 22:57:16.971790300 [routing::core core.rs:1902] Node(1b7564..) - Message unable to be acknowledged - giving up. UnacknowledgedMessage { signed_msg: SignedMessage { content: RoutingMessage { src: ClientManager(name: 12740b..), dst: ClientManager(name: 12740b..), content: UserMessagePart { 1/1, priority: 1  9a50f12bbd2465ec} }, public_id: PublicId(name: 1b7564..), signature: .. }, route: 8, timer_token: 3657 }
DEBUG 22:57:16.971790300 [routing::core core.rs:1902] Node(1b7564..) - Message unable to be acknowledged - giving up. UnacknowledgedMessage { signed_msg: SignedMessage { content: RoutingMessage { src: ClientManager(name: 13263d..), dst: ClientManager(name: 13263d..), content: UserMessagePart { 1/1, priority: 1  a9cbfbc7ea3ec2e8} }, public_id: PublicId(name: 1b7564..), signature: .. }, route: 8, timer_token: 3658 }

I'll attatch the whole log so you can take a look at it.   But yeah it seems to be having routine acknowledgement issues.
[Node.log-7.3.16.txt](https://github.com/maidsafe/safe_vault/files/345685/Node.log-7.3.16.txt)

**Comment by lionel1704** [comment]
A newly architectured vault has been released which is being integrated with the latest routing library. Hence, I'm closing this issue.
