### ISSUE TITLE
Requires routing v0.24.3 but routing only tagged up to 0.24.2

### ISSUE THREAD

**Issue by iancoleman** [maidsafe/safe_vault#535]
safe_vault cannot be built.

safe_vault has specified version 0.24.3 for routing (specified in [vault Cargo.toml:L26](https://github.com/maidsafe/safe_vault/blob/994baed5e7c992e261e10111f2c1f60d61a85276/Cargo.toml#L26))

but [routing](https://github.com/maidsafe/routing) only has tagged releases up to 0.24.2

Please either:
* tag and release v0.24.3 of routing; or
* require routing v0.24.2 for the vault (which is not as sensible as the first suggestion)

**Comment by Viv-Rajkumar** [comment]
Routing was published for [0.24.3](https://crates.io/crates/routing) to `crates.io` two days ago.

Maybe try running `cargo update` in your safe_vault repo folder before trying `cargo build --release`

I do see the explicit tag for `0.24.3` was missing from the branch that had the version published from. That should also exist [now](https://github.com/maidsafe/routing/releases)

Please reopen this issue if you're still having trouble picking the latest version.
