### ISSUE TITLE
Vault fails to bootstrap

### ISSUE THREAD

**Issue by JohannAmos** [maidsafe/safe_vault#539]
After about a day running Test Network 7 Vault, it shut down and now fails shortly after launch.

Log file:

> INFO 14:36:10.848933600 [safe_vault safe_vault.rs:99] 
> 
> Running safe_vault v0.10.5
> ==========================
> DEBUG 14:36:10.850935400 [crust::main::service service.rs:368] Network name: Some("test_network_7")
> DEBUG 14:36:14.172242100 [routing::states::bootstrapping bootstrapping.rs:202] Bootstrapping(e0cefe..) Failed to bootstrap.
> DEBUG 14:36:14.173244200 [routing::node node.rs:466] Error EventSubset("SendError(..)") sending event Core

Win 10, 64bit, official binaries

Thank you

**Comment by dirvine** [comment]
Ah TEST7 is now complete and 7b is running instead. At the moment we have not released TEST7b vaults, only launcher and demo app.

**Comment by jackquack** [comment]
I just got this same error with the latest 0.11.0

`DEBUG 02:44:23.111238710 [routing::core core.rs:1080] Disconnected(8dccac..) Failed to bootstrap.`

**Comment by slowkow** [comment]
Got the same error with 0.14.0 on Ubuntu 17.04

```bash
wget https://github.com/maidsafe/safe_vault/releases/download/0.14.0/safe_vault-v0.14.0-linux-x64.zip
unzip safe_vault-v0.14.0-linux-x64.zip
cd safe_vault-v0.14.0-linux-x64/
./safe_vault
```

```
I 17-04-30 02:54:52.219176

Running safe_vault v0.14.0
==========================
I 17-04-30 02:55:07.233105 Bootstrapping(a8e230..) Failed to bootstrap. Terminating.
```

**Comment by frabrunelle** [comment]
@slowkow: There is no testnet running at the moment. Test 16 is down, so it's normal to see this error when running SAFE Vault v0.14.0.

See the latest dev updates for more info on what we're working on 🙂 

https://safenetforum.org/c/development/updates

**Comment by cooperka** [comment]
It makes sense that this will happen when trying to connect to a production TestNet while none is running, but I'm getting the same error trying to run locally offline. I've followed the guide at https://forum.safedev.org/t/how-to-run-a-local-test-network/842 and got stuck here. Any advice?

**Comment by frabrunelle** [comment]
@cooperka Make sure to start the first Vault using the `--first` flag.

See the "Run several vaults" section.
