### ISSUE TITLE
armv not working in raspbian

### ISSUE THREAD

**Issue by btsfav** [maidsafe/safe_vault#548]
Here's what I get from the latest safe_vault-v0.11.0-armv7.zip

sudo ./safe_vault

Cannot start vault due to error : FileHandler(JsonParserError(SyntaxError("invalid syntax", 4, 24)))

**Comment by frabrunelle** [comment]
How does your `safe_vault.vault.config` file look like?

You could use a site such as [this one](http://jsonlint.com/) to check what the error is. Make sure you have double quotes around the `chunk_store_root` path. For example:

```
{
  "wallet_address": null,
  "max_capacity": 2147483648,
  "chunk_store_root": "/Users/frabrunelle/Desktop"
}
```

**Comment by btsfav** [comment]
thanks, the " " were missing for the folder!
