### ISSUE TITLE
OSX Errors: log4rs: Error deserializing component | Reference to nonexistent appender: `async_file`

### ISSUE THREAD

**Issue by capitanpiluso** [maidsafe/safe_vault#601]
OSX v10.11.6
Processor 3.2 Ghz Intel Core i5
Memory 8GB 1867 Mhz DDR3

I simply downloaded the safe_vault-v0.13.0-osx-x64, uncompressed it and I executed ./safe_vault
Was there any other preparations needed to make it work?

> ➜  safe_vault-v0.13.0-osx-x64 ./safe_vault 
> log4rs: Error deserializing component: Could not establish log file path: Io(Error { repr: Os { code: 45, message: "Operation not supported" } })
> log4rs: Error creating config: Reference to nonexistent appender: `async_file`
> log4rs: Error creating config: Reference to nonexistent appender: `async_file`
> INFO 04:49:41.605516000 [safe_vault safe_vault.rs:95] 
> 
> Running safe_vault v0.13.0
> =========================‌‌ 
> Cannot start vault due to error: FileHandler(Io(Error { repr: Os { code: 45, message: "Operation not supported" } }))
> ERROR 04:49:41.606010000 [safe_vault::vault vault.rs:51] Config file could not be parsed: Io(Error { repr: Os { code: 45, message: "Operation not supported" } })

I tried changing chmod to 777 to all files, and nothing.
Do I need to be root to execute it?

**Comment by capitanpiluso** [comment]
The problem lays with the file being executed from an Network File System.
I tested executing from an USB (to recreate the creation of the Resource Fork, to see if the spontaneous creation of hidden files were the culprit), and even though they are "com.apple.quarantine" and there are hidden files in the USB, it is executed properly without any errors.

The error I posted only happens when I attempt to execute the ./safe-vault from my home directory which is in a NFS.

**Comment by Fraser999** [comment]
It seems like this is related to running the vault on an NFS (see [this forum discussion for further details](https://safenetforum.org/t/maidsafe-dev-update-february-2-2017-test-12/12378/122?u=fraser)).

**Comment by capitanpiluso** [comment]
I know, I am the same guy lol
I was just summarizing it here the findings.

**Comment by Fraser999** [comment]
Yeah - I got that thanks 😄  I originally wrote a bit about NFS just to give some more info for whoever takes this on, but hadn't refreshed my page and only found out you'd done that already after I posted my comment!

**Comment by lionel1704** [comment]
Looks like the error is from `config_file_handler::FileHandler`.
A newly architectured vault has been released in which the `config_file_handler` dependency is not being used. Hence, I'm closing this issue.
