### ISSUE TITLE
Bandwidth approval process stops progressing at certain percentage until timeout

### ISSUE THREAD

**Issue by anon-safe** [maidsafe/safe_vault#604]
We've had at least three independent reports about this. The approval process starts and runs just fine, then at a certain percentage bandwidth drops to 0 and eventually the vault terminates (timeout).

**Report 1**

![image](https://cloud.githubusercontent.com/assets/21228504/22761843/d5ce01a4-ee5c-11e6-9849-916b361f8ec5.png)

**Report 2**

`Running safe_vault v0.13.0

    INFO 22:54:50.897796597 [routing::states::node node.rs:1240] Node(005fa0..()) Requesting a relocated name from the network. This can take a while.
    INFO 22:54:51.309089922 [routing::states::node node.rs:1890] Node(32e12b..()) Received relocated name. Establishing connections to 11 peers.
    INFO 22:54:52.161236171 [routing::states::node node.rs:1031] Node(32e12b..()) Starting approval process to test this node's resources. This will take at least 300 seconds.
    INFO 22:55:21.309252463 [routing::states::node node.rs:2316] Node(32e12b..()) 0/11 resource proof response(s) complete, 4% of data sent. 380/410 seconds remaining.

    --SNIP--

    INFO 22:59:21.310867704 [routing::states::node node.rs:2316] Node(32e12b..()) 0/11 resource proof response(s) complete, 77% of data sent. 140/410 seconds remaining.
    INFO 22:59:51.311123534 [routing::states::node node.rs:2316] Node(32e12b..()) 0/11 resource proof response(s) complete, 86% of data sent. 110/410 seconds remaining.
    INFO 23:00:21.311316914 [routing::states::node node.rs:2316] Node(32e12b..()) 0/11 resource proof response(s) complete, 86% of data sent. 80/410 seconds remaining.
    INFO 23:00:51.311555772 [routing::states::node node.rs:2316] Node(32e12b..()) 0/11 resource proof response(s) complete, 86% of data sent. 50/410 seconds remaining.
    INFO 23:01:21.311733816 [routing::states::node node.rs:2316] Node(32e12b..()) 0/11 resource proof response(s) complete, 86% of data sent. 20/410 seconds remaining.
    INFO 23:01:41.309229807 [routing::states::node node.rs:2350] Node(32e12b..()) Failed to get approval from the network. 0/11 resource proof response(s) complete, 86% of data sent. Terminating node.
`

**Comment by anon-safe** [comment]
Ah it seems after 300 seconds, the bandwidth test fails and so the vault is rejected! So it's not really a bug...

**Comment by afck** [comment]
Yes, exactly: After 300 seconds the vaults don't accept any packets anymore. The remaining time is just a buffer to wait for the response.
We'll try to improve the log messages to make this more clear.

**Comment by anon-safe** [comment]
Yeah makes sense. Was it changed from Test 12 to Test 12b? Cause the first time my vault was able to join, and it took a bit longer than the 300 sec.

**Comment by afck** [comment]
No, that timeout didn't change, I think. Maybe the message itself just took a while to accumulate and be sent to you. (After the 300 s, the nodes vote on whether to accept the new node, and only after the vote, they send the response.)

**Comment by lionel1704** [comment]
A newly architectured vault has been released. Hence, I'm closing this issue.
