### ISSUE TITLE
Safe Vault 0.14 will not launch 

### ISSUE THREAD

**Issue by Blindsite** [maidsafe/safe_vault#616]
Okay first off I have UPnP enabled but the SAFE vault wouldn't connect so I set the port to a forwarded port I had set and tried launching it.   Now it won't even launch and windows is complaining that it doesn't have permission to launch the file or path of safe_vault.exe.   My antivirus is also acting up.   So not only can I not connect to the network but I cannot launch the vault software in the first place.

**Comment by octol** [comment]
There is a new version out which is completely re-architectured. Hopefully it should work better now!

**Comment by lionel1704** [comment]
As previously mentioned, a new version has been released which was completely re-written. Hence, I'm closing this issue.
