### ISSUE TITLE
Error with address when starting vault

### ISSUE THREAD

**Issue by bretmette** [maidsafe/safe_vault#655]
I input my address into the .env file (I used a bitcoin address which is 34 characters) then started up the vault and I get the following error:
`
Cannot start vault due to error: FileHandler(JsonParser(ErrorImpl { code: Message("invalid type: string \"REDACTED\", expected an array of length 32"), line: 2, column: 58 }))
`

Is there a SAFE COIN address or some other "wallet" address I should be using or is this a bug?

I am running commit 2c3935ce78bd3d7508dff40d2e1f18fd5d1526a9 and starting safe_vault using docker-compose

`docker-compose -f installer/docker/docker-compose.yml up`

**Comment by bretmette** [comment]
Here is my .env file

```
RUST_LOG=safe_vault=debug
SAFE_VAULT_HARD_CODED_CONTACTS=
SAFE_VAULT_WHITELISTED_NODE_IPS=
SAFE_VAULT_WHITELISTED_CLIENT_IPS=
SAFE_VAULT_TCP_ACCEPTOR_PORT=null
SAFE_VAULT_FORCE_ACCEPTOR_PORT_IN_EXT_EP=false
SAFE_VAULT_SERVICE_DISCOVERY_PORT=null
SAFE_VAULT_BOOTSTRAP_CACHE_NAME=null
SAFE_VAULT_NETWORK_NAME=null
SAFE_VAULT_DISABLE_REACHABILITY_REQUIREMENT=true
SAFE_VAULT_ALLOW_MULTIPLE_LAN_NODES=true
SAFE_VAULT_DISABLE_CLIENT_RATE_LIMITER=true
SAFE_VAULT_DISABLE_RESOURCE_PROOF=true
SAFE_VAULT_MIN_SECTION_SIZE=1
SAFE_VAULT_WALLET_ADDRESS=1F1tAaz5x1HUXrCNLbtMDqcw6o5GNn4xqX
SAFE_VAULT_MAX_CAPACITY=null
SAFE_VAULT_DISABLE_MUTATION_LIMIT=true
SAFE_VAULT_LOG_LEVEL_ASYNC_CONSOLE_FILTERS=info
SAFE_VAULT_LOG_LEVEL_ROOT=error
SAFE_VAULT_LOG_LEVEL_CRUST=debug
SAFE_VAULT_LOG_LEVEL_ROUTING=trace
SAFE_VAULT_LOG_LEVEL_ROUTING_STATS=trace
SAFE_VAULT_LOG_LEVEL_SAFE_VAULT=trace
```

**Comment by ustulation** [comment]
Hey @bretmette, wallet is currently just a placeholder, we are not there yet so vaults (or safenet in general) don't deal with safecoin just now. Pls leave that null as u can see it's [optional](https://github.com/maidsafe/safe_vault/blob/master/src/config_handler.rs#L28)
