### ISSUE TITLE
Ubuntu package safe-vault not found

### ISSUE THREAD

**Issue by trecement** [maidsafe/safe_vault#676]
On following instructions in installer/README.md, I added the necessary repos as in [apt.maidsafe.net](http://apt.maidsafe.net)

However the package `safe-vault ` is not found.
BTW neither is `safe_vault,` there seems to be some inconsistency in this documentation between safe-vault and safe_vault.

Related to issue #653 ?

**Comment by calumcraig** [comment]
Can confirm the same behaviour on my Linux Mint 19 machine. Added the repos referenced to at http://apt.maidsafe.net/ but `safe-vault` does not become available. The three other packages mentioned `safe-browser web-hosting-manager safe-mail-tutorial` do become available for install via `sudo apt-get install`.
![image](https://user-images.githubusercontent.com/44327924/52701053-3a73fa80-2f71-11e9-9327-c14db037bed7.png)
![image](https://user-images.githubusercontent.com/44327924/52701103-59728c80-2f71-11e9-94df-fed6476f2f29.png)

**Comment by lionel1704** [comment]
A newly architectured vault has been released. The repo has been updated without the installer documentation.
Hence, I'm closing this issue.
