### ISSUE TITLE
Rename elder structs

### ISSUE THREAD

**Issue by Fraser999** [maidsafe/safe_vault#758]
We need to make the following changes:
1. Rename `SourceElder` to `ClientHandler`
2. Split `DestinationElder` into `IDataHandler` (deals with the meta-info about `IData`), `IDataHolder` (owns the `IData` chunkstore), `MDataHandler`, and `ADataHandler`.
3. Rename `Account` to `AuthKeys` (ensure there are no instances of the term "account" left in the source code after the change)

**Comment by madadam** [comment]
Closed via #764 and #765.
