### ISSUE TITLE
Check App permissions

### ISSUE THREAD

**Issue by Fraser999** [maidsafe/safe_vault#761]
We need to update the vaults so that when handling requests from Apps they check the following:
* if the request is a mutation of any kind, the app should have an entry in the `Account` for its owner, and the value of `transfer_coins` must be true to allow the mutation.
* if the request is non-mutating, but for unpublished data (`UnpubImmutableData`, `Unpub{Seq|Unseq}AppendOnlyData`, or `{Seq|Unseq}MutableData`), the app should have an entry in the `Account` for its owner (the value of `transfer_coins` doesn't affect this).

For published data, non-mutating requests don't need such checks.

**Comment by nbaksalyar** [comment]
>the value of transfer_coins must be true to allow the mutation.

I wonder if this should be more fine-grained? I.e. have a permission for allowing coin transfers (`transfer_coins`) and a separate permission allowing mutations from apps (e.g., `mutation`).
