### ISSUE TITLE
Fix config_handler::test::smoke and add it to CI

### ISSUE THREAD

**Issue by octol** [maidsafe/safe_vault#789]
The failing test `config_handler::test::smoke` serves as a check that when `Config` is updated, `ARGS` should also be. The tests only runs without `--features mock` and hence isn't tested by CI.

We should fix the test and make sure it runs as part of CI.

**Comment by alanpoon** [comment]
The smoke test is fixing again.
failures:

---- config_handler::test::smoke stdout ----
thread 'config_handler::test::smoke' panicked at 'assertion failed: `(left == right)`
  left: `232`,
 right: `216`: Ensure that any changes to `Config` are reflected in `ARGS`.', src/config_handler.rs:244:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:208
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:336
   7: safe_vault::config_handler::test::smoke
   8: safe_vault::config_handler::test::smoke::{{closure}}
   9: core::ops::function::FnOnce::call_once
  10: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/liballoc/boxed.rs:702
  11: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:87
  12: test::run_test::run_test_inner::{{closure}}
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/panicking.rs:272
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/panic.rs:388
             at src/libtest/lib.rs:1468


failures:
    config_handler::test::smoke

test result: FAILED. 7 passed; 1 failed; 1 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--lib'
The command '/bin/sh -c rustup component add rustfmt clippy &&     rustup target add x86_64-unknown-linux-musl &&     scripts/tests --verbose' returned a non-zero code: 101
Makefile:13: recipe for target 'build-container' failed
make: *** [build-container] Error 101

system: Ubuntu 18.04
