### ISSUE TITLE
Handle TestCreateBalance RPC

### ISSUE THREAD

**Issue by lionel1704** [maidsafe/safe_vault#796]
In order to create an account, a user must have an already existing coin balance. For phase 1 (i.e. local vaults) in order to allow users to create an account and test balance transfers etc. there will be a feature-gated `TestCreateBalance` RPC as follows.
```
TestCreateBalance {
     owner: PublicKey,
     amount: Coins
}
```
When this request arrives in the vault, a new balance is inserted at the key's address preloaded with the specified amount of coins.

**Comment by octol** [comment]
Superseded by #798
