### ISSUE TITLE
Epic: Bootstrap as a client (2 days)

### ISSUE THREAD

**Issue by jeanphilippeD** [maidsafe/safe_vault#845]
Single task:

  => (Pretty much what happen for phase 1 => Small).
  => We have N hardcoded contacts (phase 2.a -> e.g. 7 vaults)
     Meaning that in the config file we need to list all the connection infos for these Vaults along with their certificates / public keys.
  => The challenge mechanism wouldn't change.
  => Make sure all hardcoded contacts are connected and we maintain them as a list of Elders to which we send the requests and getting responses from.

  => All the way to full client (Can do get and puts and other things)
  => hard coded contacts.
  => eventually vaults need to validate client are valid.
  ==> can bypass check for now as all clients valid.

  - Do we want to have automatic configuration for multiple vaults?
    - Ideally: setup as easy as Phase 1 if possible.
    - We can decide on this when we're closer to the release (this can be a task in the Vaults: decide what to do about the config file while running multiple Vaults?).

**Comment by lionel1704** [comment]
This depends on #842 and #837.
However we can create the setup to check if a client is able to connect-to and send messages to multiple vaults using an array of connection information in the `safe_core.config` file.

**Comment by maqi** [comment]
Work has been done to have `bootstrapable client connecting to vault network` .
