### ISSUE TITLE
Epic: SCL: process request response. (1-2 days)

### ISSUE THREAD

**Issue by jeanphilippeD** [maidsafe/safe_vault#846]
=> Expand `ConnectionGroup` to support more Elders, and send requests to all of them.
  => *Now just a filter: take the first response assuming no malice.* We don't do any accumulation.
  => Pretty much what is happening in phase 1.

  - Send requests 2/3rds of Vaults in case of mutations?
     - Should be OK for Phase 2.a to send to all elders.

  - Make sure we get the responses from all of the Vault.

**Comment by maqi** [comment]
TestClient has been updated to send requests to all connected vaults and expect responses from all vaults.
