### ISSUE TITLE
Make sure the real routing with mock parsec works

### ISSUE THREAD

**Issue by m-cat** [maidsafe/safe_vault#875]
+ Currently mock routing works.
+ Use mock_parsec feature flag in routing? (No access to mock_parsec (?)).
+ Maybe routing quic_p2p needs to be called to make progress? (Maybe not a problem at the time since only 1 vault.)
 + May require debugging now that we're using routing to do something.
 + Eventually, but not initially, the routing instance would handle both network and parsec events.

**Comment by maqi** [comment]
work addressed by PR 910
