### ISSUE TITLE
Run multiple vaults with mock_routing and only send request to some vaults 2/3

### ISSUE THREAD

**Issue by Yoga07** [maidsafe/safe_vault#876]
- Need to make mock_routing work with multiple vault.
- Mock routing vote_for could be a simple send first one to all vaults and filter other ones. (Alternative could use mock_parsec but maybe more complicated).
- Assume client send same request to 2/3 vaults.
- All vaults reply the same even if they did not get the requests.

**Comment by maqi** [comment]
task completed.
