### ISSUE TITLE
Support RPC to request elders connection information

### ISSUE THREAD

**Issue by nbaksalyar** [maidsafe/safe_vault#893]
This RPC should use API provided by Routing in maidsafe/routing#1889 and return the connection information to a bootstrapped client. The request should contain the client's public ID and the response should contain connection infos for ClientHandlers in a section corresponding to the client's ID (that will be the single section in Phase 2a):
```rust
struct ConnectionInfoRequest { client_id: safe_nd::ClientPublicId };
struct ConnectionInfoResponse { connection_infos: Vec<routing::ConnectionInfo> };
```

**Comment by maqi** [comment]
Has been covered by the `HandshakeRequest::Bootstrap` and `HandshakeResponse::Bootstrap` RPCs.
