### ISSUE TITLE
[fleming][no-parsec] Intermittent PUT bugs

### ISSUE THREAD

**Issue by joshuef** [maidsafe/safe_vault#958]
Intermittent issue can be seen when running a PUT:

```[Error] NetDataError - Failed to PUT Sequenced Append Only Data: Error(CoreError(Forbidden operation requested - CoreError::OperationForbidden))```

And `AccessDenied` Errors can be seen ocassionally. (The former being more common).

Likely related to data being out of sync with different elders w/ consensus removed for now.

**Comment by lionel1704** [comment]
This has been resolved by maidsafe/safe_client_libs#1184
