### ISSUE TITLE
Implement data handling responsibilities of Adults

### ISSUE THREAD

**Issue by lionel1704** [maidsafe/safe_vault#973]
An adult should be given responsibilities to hold Immutable Data chunks. When the Elders in it's section (IDataHandlers) request a chunk from us (IDataHolders) the Adult should return the chunk to the Elders who will respond back to the Client.

- [x] send IData chunks to be held at Adults from the IData handler
- [x] handle store IData chunk requests at the adults
- [x] on receiving a GetIData request forward the request to the Adult
- [x] process the response from the Adults and send IData back to the client

**Comment by ravinderjangra** [comment]
closed by #980 & #985
